# Generated by Django 4.1.7 on 2023-08-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_order_receipt'),
        ('shopapp', '0008_product_created_by'),
    ]

    operations = [
    ]
