# Generated by Django 4.1.7 on 2023-08-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_merge_0008_order_receipt_0008_product_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='receipt',
        ),
    ]
