# Generated by Django 4.1.7 on 2023-08-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_alter_product_options_remove_order_receipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
